plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'db/migrations/**/*'

# Pragmatic rules - focus on consistency over strictness
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'Rakefile'

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Layout/LineLength:
  Max: 120

# RSpec specific
RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 5

# Allow string descriptions for API route specs
RSpec/DescribeClass:
  Enabled: false

# Allow expect().not_to receive() pattern
RSpec/MessageSpies:
  Enabled: false

# Allow iterating with expectations for simple cases
RSpec/IteratedExpectation:
  Enabled: false
