source 'https://rubygems.org'

ruby '3.4.2'

# Runtime dependencies
gem 'dotenv', '~> 3.1'
gem 'puma', '~> 6.5'
gem 'rack-cors', '~> 2.0'
gem 'rack-protection', '~> 4.1'
gem 'rackup', '~> 2.2'
gem 'sequel', '~> 5.87'
gem 'sinatra', '~> 4.1'
gem 'sinatra-contrib', '~> 4.1'
gem 'sqlite3', '~> 2.5'

# Development and test dependencies
group :development, :test do
  gem 'rack-test', '~> 2.1'
  gem 'rerun', '~> 0.14'
  gem 'rspec', '~> 3.13'
  gem 'rubocop', '~> 1.70', require: false
  gem 'rubocop-rspec', '~> 3.4', require: false
end
